---
title: Kai Gradert
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  blog_tags:
    title: Tags
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: default
- scope:
    path: ''
    type: blog_tags
  values:
    layout: default
description: 'I am a designer, photographer, and timelapse creator. My interests range
  from photography to technology. I currently live in California. '
author: Kai Gradert
bio: Designer, Photographer, Dad, Husband
keywords: User Experience, Visual Design, UX, Design, Google, Apple, Consulting
email: kai.gradert@gmail.com
gravatar: 11e4ed5d85b6bccce20f8f86476785d6
url: http://kaigradert.com
contact:
  Twitter: https://twitter.com/kaigradert
  AngelList: https://angel.co/kai
  LinkedIn: http://www.linkedin.com/in/kaigradert
  Instagram: http://instagram.com/kaikemono
  Flickr: http://www.flickr.com/photos/kaigradert/sets/
  SmugMug: https://kaigradert.smugmug.com/
baseurl: 
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
- jekyll-feed
- jekyll-sitemap
exclude:
- ".config.codekit3"
- ".gitignore"
- config.codekit3
- Gemfile
- Gemfile.lock
- styles/global.sass
